import { JsonLd } from "@/components/site/JsonLd";
import { IndustryV4 } from "@/components/site/v4/IndustryV4";
import { v4FontClass } from "@/components/site/v4/fonts";
import { industryJsonLd, industryMetadata, industryPageBySlug } from "@/lib/seo/industries";

// Generated by scripts/gen-industry-routes.mjs — edit the content file instead.
const page = industryPageBySlug("softver-za-frizerski-salon-i-berbernicu");

export const metadata = industryMetadata(page);

export default function Page() {
  return (
    <div className={v4FontClass}>
      <JsonLd data={industryJsonLd(page)} />
      <IndustryV4 page={page} />
    </div>
  );
}
